## .gitlab-ci-semver.labels.yml

# commit-message-regexp: (?s)(?:^|\n)See merge request (?:\w[\w.+/-]*)?!(\d+)
# dotenv-file: ""
# dotenv-var: version
# fail: false
# fetch-tags: true
# gitlab-token-env: GITLAB_TOKEN
# gitlab-url: $CI_SERVER_URL or "https://gitlab.com"
# initial-label-regexp: (?i)initial.release|semver(.|::)initial
# initial-version: 0.0.0
# major-label-regexp: (?i)(major|breaking).release|semver(.|::)(major|breaking)
# minor-label-regexp: (?i)(minor|feature).release|semver(.|::)(minor|feature)
# patch-label-regexp: (?i)(patch|fix).release|semver(.|::)(patch|fix)
# prerelease-label-regexp: (?i)pre.?release
# project: $CI_PROJECT_ID
# remote-name: origin
# work-tree: .
